CREATE TABLE IF NOT EXISTS "Project" (
	"id" INTEGER NOT NULL UNIQUE,
	"name" VARCHAR NOT NULL,
	"description" TEXT,
	"thumbnail" VARCHAR,
	"background" VARCHAR,
	"creation_date" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"mute" BOOLEAN NOT NULL DEFAULT FALSE,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "Column" (
	"id" INTEGER NOT NULL UNIQUE,
	"name" VARCHAR NOT NULL,
	"color" VARCHAR,
	"id_project" INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("id_project") REFERENCES "Project"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "Card" (
	"id" INTEGER NOT NULL UNIQUE,
	"title" VARCHAR NOT NULL,
	"description" TEXT,
	"color" VARCHAR,
	"notify" BOOLEAN NOT NULL DEFAULT FALSE,
	"start_date" DATETIME,
	"end_date" DATETIME,
	"id_column" INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("id_column") REFERENCES "Column"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "CardHistory" (
	"id" INTEGER NOT NULL UNIQUE,
	"text" TEXT NOT NULL,
	"update_time" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"id_card" INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("id_card") REFERENCES "Card"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
